name: Events Demo 1
on:
  pull_request:
    types:
      - opened

  workflow_dispatch:
  push:
    branches:
      - main # matches "main"
      - "dev-*" # matches "dev-<anything>"
      - "feat/**" # matches "feat/<anything> and feat/<anything>/<anything>"
    paths-ignore:
      - ".github/workflows/*"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Output event data
        run: echo "${{ toJSON(github.event) }}"
      - name: Get code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Test code
        run: npm run test
      - name: Build code
        run: npm run build
      - name: Deploy project
        run: echo "Deploying..."
